blog/urls.py
# -*- coding: utf-8 -*-
"""
#Python 3.6
-------------------------------------------------
   Project Name:    securityproject
   File Name:       urls.py
   Description :
   Author :         flowerhost
   date:            2020/5/6          
-------------------------------------------------
   Change Activity:
                    2020/5/6:
-------------------------------------------------
"""
__author__ = 'flowerhost'

"""定义blog的URL模式"""

from django.urls import path, re_path

from . import views

# 在2.1版本中必须增加的一条代码
app_name = 'blog'

urlpatterns = [
    # 所有文章列表
    path('', views.ArticleListView.as_view(), name='article_list'),
    # 展示文章详情
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
    # 草稿箱
    path('draft/', views.ArticleDraftListView.as_view(), name='article_draft_list'),
    # 已发表文章列表（含编辑）
    path('published/', views.PublishedArticleListView.as_view(), name='published_article_list'),
    # 更新文章
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/update/$', views.ArticleUpdateView.as_view(),
            name='article_update'),
    # 创建文章
    re_path(r'^article/create/$', views.ArticleCreateView.as_view(), name='article_create'),
    # 发表文章
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/publish/$', views.article_publish, name='article_publish'),
    #  删除文章
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/delete$', views.ArticleDeleteView.as_view(),
            name='article_delete'),
    # 展示类别列表
    # re_path(r'^category/$',
    #         views.ArticleDraftListView.as_view(), name='category_list'),

    # 展示类别详情
    re_path(r'^category/(?P<slug>[-\w]+)/$',
            views.CategoryDetailView.as_view(), name='category_detail'),

]

securityproject/urls.py
from django.contrib import admin
from django.urls import include, path
# 2020-05-06 新增bolg app
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('index/', include('capital_management.urls', namespace='capital_management')),
    path('captcha', include('captcha.urls')),  # 登陆界面图形验证功能
    path('select2/', include('select2.urls')),  # 下拉菜单筛选功能
    path('blog/', include('blog.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from unidecode import unidecode
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField
import datetime


class Category(models.Model):
    """文章分类"""
    name = models.CharField(max_length=30, unique=True, verbose_name='分类名')
    slug = models.SlugField(max_length=40, verbose_name='slug')
    parent_category = models.ForeignKey('self', verbose_name='父级分类', blank=True, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('blog:category_detail', args=[self.slug])

    def has_child(self):
        if self.category_set.all().count() > 0:
            return True

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = "分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """文章标签集合"""
    name = models.CharField(max_length=30, unique=True, verbose_name='标签名')
    slug = models.SlugField(max_length=40, verbose_name='slug')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag_detail', args=[self.slug])

    def get_article_count(self):
        return Article.objects.filter(tags__slug=self.slug).count()

    class Meta:
        ordering = ['name']
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """文章模型"""
    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表'),
    )

    title = models.CharField(max_length=200, unique=True, verbose_name='标题')
    slug = models.SlugField(max_length=60, blank=True, verbose_name='slug')
    body = RichTextUploadingField(verbose_name='正文')
    pub_date = models.DateTimeField(verbose_name='发布时间', null=True)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    mod_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='p', verbose_name='文章状态')
    views = models.PositiveIntegerField(verbose_name='浏览量', default=0)
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE, blank=False, null=False)

    category = models.ForeignKey(Category, verbose_name='文章类别', on_delete=models.CASCADE, default=0, blank=False, null=False)
    tags = models.ManyToManyField(Tag, verbose_name='内容标签', blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id or not self.slug:
            # Newly created object, so set slug
            self.slug = slugify(unidecode(self.title))

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[str(self.pk), self.slug])

    def clean(self):
        # Don't allow draft entries to have a pub_date
        if self.status == 'd' and self.pub_date is not None:
            self.pub_date = None
            # Raise ValidationError('草稿没有发布日期，发布日期已清空。')
        if self.status == 'p' and self.pub_date is None:
            self.pub_date = datetime.datetime.now()

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def published(self):
        self.status = 'p'
        self.pub_date = datetime.datetime.now()
        self.save(update_fields=['status', 'pub_date'])

    class Meta:
        ordering = ['-pub_date']
        verbose_name = "文章"
        verbose_name_plural = verbose_name

blog/forms.py
# -*- coding: utf-8 -*-
"""
#Python 3.6
-------------------------------------------------
   Project Name:    securityproject
   File Name:       forms.py
   Description :
   Author :         flowerhost
   date:            2020/5/7          
-------------------------------------------------
   Change Activity:
                    2020/5/7:
-------------------------------------------------
"""
__author__ = 'flowerhost'

from django import forms
from .models import Article
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ['author', 'views', 'slug', 'pub_date']

        widgets = dict(title=forms.TextInput(attrs={'class': 'form-control'}),
                       body=CKEditorUploadingWidget(attrs={'class': 'form-control'}),
                       status=forms.Select(attrs={'class': 'form-control'}),
                       category=forms.Select(attrs={'class': 'form-control'}),
                       tags=forms.CheckboxSelectMultiple(attrs={'class': 'multi-checkbox'}))

blog/views.py
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Article, Category
from django.shortcuts import get_object_or_404, redirect
from .forms import ArticleForm
from django.http import Http404
from django.core.paginator import Paginator
# from django.contrib.auth.decorators import login_required
# from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy


class ArticleListView(ListView):
    paginate_by = 100000

    def get_queryset(self):
        return Article.objects.filter().order_by('-mod_date')


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.viewed()
        return obj


class ArticleDraftListView(ListView):
    template_name = "blog/article_draft_list.html"
    paginate_by = 3

    def get_queryset(self):
        return Article.objects.filter(author=self.request.user).filter(status='d').order_by('-pub_date')


class PublishedArticleListView(ListView):
    template_name = "blog/published_article_list.html"
    paginate_by = 100

    def get_queryset(self):
        return Article.objects.filter(author=self.request.user).filter(status='p').order_by('-pub_date')


class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "blog/article_update_form.html"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.author != self.request.user:
            raise Http404()
        return obj


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'blog/article_create_form.html'

    # Associate form.instance.user with self.request.user
    def form_valid(self, form):

        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blog:article_list')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.author != self.request.user:
            raise Http404()
        return obj


def article_publish(request, pk, slug1):
    article = get_object_or_404(Article, pk=pk, author=request.user)
    article.published()
    return redirect(reverse("blog:article_detail", args=[str(pk), slug1]))


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.object.has_child():
            articles = Article.objects.filter()
            categories = self.object.category_set.all()
            for category in categories:
                queryset = Article.objects.filter(category=category.id).order_by('-pub_date')
                articles.union(queryset)
        else:
            articles = Article.objects.filter(category=self.object.id).order_by('-pub_date')

        paginator = Paginator(articles, 100)
        page = self.request.GET.get('page')
        page_obj = paginator.get_page(page)
        context['page_obj'] = page_obj
        context['paginator'] = paginator
        context['is_paginated'] = True
        return context

templates/blog/article_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ article }}"?</p>
    <input type="submit" value="Confirm" />
</form>

templates/blog/article_create_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}新建笔记{% endblock %}

{% block css %}
     <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        操盘笔记
        <small>创建</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">操盘笔记</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
    <div class="col-md-12">
      <div class="box box-success">
        <div class="box-body">
            <form class="form-horizontal" method="post" role="form" action="" >
              <div class="box-body">
                  {% csrf_token %}
                  {{ form.media }}
                  {{ form }}
              </div>
              <div class="box-footer">
                <button type="submit" class="btn btn-default">取消</button>
                <button type="submit" class="btn btn-info pull-right">提交</button>
              </div>
              <!-- /.box-footer -->
            </form>

        </div>
        <!-- /.box-body -->
      </div>
   </div>
{% endblock %}

{% block script %}

<!-- DataTables -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- page script -->

{% endblock %}

templates/blog/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日志详情{% endblock %}

{% block css %}
     <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        笔记
        <small>详情</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">笔记详情</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
   <div class="col-md-12">

    <!-- BAR CHART -->
      <div class="box box-success">
        <div class="box-header with-border">
            <p>类别：
                {% if article.category.parent_category %}
                    <a href="{% url 'blog:category_detail' article.category.parent_category.slug %}">
                        {{ article.category.parent_category.name }}
                    </a>/
                {% endif %}
                    <a href="{% url 'blog:category_detail' article.category.slug %}">{{ article.category }}</a>
            </p>
        </div>
        <div class="box-body">
            <h3 class="box-title text-blue">
                {{ article.title }}
                {% if article.status == "d" %}
                    (草稿)
                {% endif %}
            </h3>
            {% if article.status == "p" %}
                <p class="text-gray">发布于{{ article.pub_date|date:"Y-m-d" }}  浏览{{ article.views }}次</p>
            {% endif %}
            <p>{{ article.body|safe }}</p>

            <p>标签：
                {% for tag in article.tags.all %}
                    <a>{{ tag.name }}</a>
                {% endfor %}
            </p>
            {% if article.author == request.user %}
                {% if article.status == "d" %}
                    <a href="{% url 'blog:article_publish' article.id article.slug %}">发布</a>
                {% endif %}
                <a href="{% url 'blog:article_update' article.id article.slug %}">编辑</a>
                <a href="{% url 'blog:article_delete' article.id article.slug %}">删除</a>
            {% endif %}
        </div>

        <!-- /.box-body -->
      </div>
   </div>
{% endblock %}

{% block script %}

<!-- DataTables -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- page script -->

{% endblock %}

templates/blog/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}笔记列表{% endblock %}

{% block css %}
     <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        笔记列表
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">笔记列表</li>
      </ol>
    </section>
    <!--  删除线 -->
    <style>
        .line_through{
          text-decoration:line-through;
            color: blue;
      }
    </style>
    <!-- end 删除线 -->
{% endblock %}

{% block content %}

   <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

        <div class="box">
        <div class="box-header">
            <li><a href="{% url 'blog:article_create' %}"><i class="fa fa-file-text"></i> <span>新建笔记</span></a></li>
        </div>
        <!-- /.box-header -->
        <div class="box-body">

        {% if page_obj %}

            <table id="blog" class=" table table-bordered table-striped ">
                <thead class="text-center text-muted bg-danger">
                    <tr>
                        <th>序号</th>
                        <th>标题</th>
                        <th>类别</th>
                        <th>状态</th>
                        <th>标签集合</th>
                        <th>更新时间</th>
                        <th>发布日期</th>
                        <th>查看</th>
                        <th>更新</th>
                        <th>删除</th>
                    </tr>
                </thead>
                <tbody>

                  {% for article in page_obj %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td>
                            {{ article.title }}
                        </td>
                        <td>
                            {{ article.category.name }}
                        </td>
                        <td>
                            {{ article.get_status_display }}
                        </td>
                        <td>
                            {% for tag in article.tags.all %}
                                {{ tag.name }}
                            {% endfor %}
                        </td>
                        <td>
                            {{ article.mod_date }}
                        </td>
                        <td>
                            {{ article.pub_date | date:"Y-m-d" }}
                        </td>
                        <td>
                            <a href="{% url 'blog:article_detail' article.id article.slug%}"><span class="glyphicon glyphicon-eye-open"></span> </a>
                        </td>
                        <td>
                            <a href="{% url 'blog:article_update' article.id article.slug %}"><span class="glyphicon glyphicon-wrench"></span> </a>
                        </td>
                        <td>
                            <a href="{% url 'blog:article_delete' article.id article.slug %}"><span class="glyphicon glyphicon-trash"></span> </a>
                        </td>
                  {% endfor %}
                    </tr>


                </tbody>
                <tfoot>

                </tfoot>
            </table>
        {% else %}
            <p>没有文章</p>
        {% endif %}

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
        </div>
    <!-- /.col -->
      </div>
    <!-- /.row -->
    </section>

{% endblock %}

{% block script %}

<!-- DataTables -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- page script -->
<script>
    $(function () {
        $('#blog').DataTable({
             "paging"      : true,       <!-- 允许分页 -->
             "lengthChange": true,       <!-- 允许改变每页显示的行数 -->
             "searching"   : true,       <!-- 允许内容搜索 -->
             "ordering"    : true,       <!-- 允许排序 -->
             "info"        : true,       <!-- 显示信息 -->
             "autoWidth"   : true,       <!-- 固定宽度 -->



             "pagingType"  : "full_numbers",  <!-- 显示尾页和首页 -->

              "language": {
                        //"info": "当前第_PAGE_页，共 _PAGES_页",
                        "sInfo": "当前显示第 _START_ 到第 _END_ 条，共 _TOTAL_ 条",
                        "sInfoFiltered": "(从_MAX_条筛选 )",
                        "sInfoEmpty": "共筛选到0条",
                        "sSearch": "搜索:",
                        "sLengthMenu": "每页显示 _MENU_ 条",
                        "sZeroRecords": "未筛选到相关内容",
                        "paginate": {
                            "sFirst": "首页",  //首页和尾页必须在pagingType设为full_numbers时才可以
                            "sLast": "尾页",
                            "sPrevious": "上一页",
                            "sNext": "下一页",
                            "first": "First page",
                            "last": "Last page",
                            "next": "Next page",
                            "previous": "Previous page"
                        }

              }
        });
        $('#evaluate').colResizable({
            liveDrag: true, //实现实时拖动，可看见拖动轨迹
            draggingClass: "dragging", //防止拖动出现虚标线
            resizeMode: 'flex',
        });
    });

</script>

{% endblock %}

templates/blog/article_update_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}更新笔记{% endblock %}

{% block css %}
     <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        操盘笔记
        <small>更新</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">操盘笔记</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
    <div class="col-md-12">
      <div class="box box-success">
        <div class="box-body">
            <form class="form-horizontal" method="post" role="form" action="">
              <div class="box-body">
                  {% csrf_token %}
                  {{ form.media }}
                  {{ form }}
              </div>
              <div class="box-footer">
                <button type="submit" class="btn btn-default">取消</button>
                <button type="submit" class="btn btn-info pull-right">提交</button>
              </div>
              <!-- /.box-footer -->
            </form>

        </div>
        <!-- /.box-body -->
      </div>
   </div>
{% endblock %}

{% block script %}

<!-- DataTables -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- page script -->

{% endblock %}

templates/blog/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}笔记清单{% endblock %}

{% block css %}
     <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
{% endblock %}

{% block content %}
   <div class="col-md-12">

        <p>文章类别:
            {% if category.parent_category %}
                <a href="{% url 'blog:category_detail' category.parent_category.slug %}">{{ category.parent_category.name }}</a> /
            {% endif %}
                <a href="{% url 'blog:category_detail' category.slug %}">{{ category }}</a>
        </p>
        <h3>笔记清单</h3>

        {% if page_obj %}
            <ul>
                {% for article in page_obj %}
                    <li><a href="{% url 'blog:article_detail' article.id article.slug %}"> {{ article.title }}</a> {{ article.pub_date | date:"Y-m-j" }}</li>
                {% endfor %}
            </ul>

            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">前一页</a></li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">前一页</span></li>
                    {% endif %}

                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active"><span class="page-link"> {{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a></li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">下一页</span></li>
                    {% endif %}
                </ul>
            {% endif %}

        {% else %}
            <p>No article yet.</p>
        {% endif %}

   </div>
{% endblock %}

{% block script %}

<!-- DataTables -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- page script -->

{% endblock %}

templates/blog/published_article_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}操作日志{% endblock %}

{% block css %}
     <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        操作日志
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">操作日志</li>
      </ol>
    </section>
    <!--  删除线 -->
    <style>
        .line_through{
          text-decoration:line-through;
            color: blue;
      }
    </style>
    <!-- end 删除线 -->
{% endblock %}

{% block content %}

   <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

        <div class="box">
        <div class="box-header">
         <h3 class="box-title">操作日志<small>(每日功课)</small></h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">

        {% if page_obj %}

            <table id="blog" class=" table table-bordered table-striped ">
                <thead class="text-center text-muted bg-danger">
                    <tr>
                        <th>序号</th>
                        <th>标题</th>
                        <th>类别</th>
                        <th>发布日期</th>
                        <th>查看</th>
                        <th>修改</th>
                        <th>删除</th>
                    </tr>
                </thead>
                <tbody>

                  {% for article in page_obj %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td>
                            {{ article.title }}
                        </td>
                        <td>
                            {{ article.category.name }}
                        </td>
                        <td>
                            {{ article.pub_date | date:"Y-m-d" }}
                        </td>
                        <td>
                            <a href="{% url 'blog:article_detail' article.id article.slug%}"><span class="glyphicon glyphicon-eye-open"></span> </a>
                        </td>
                        <td>
                            <a href="{% url 'blog:article_update' article.id article.slug %}"><span class="glyphicon glyphicon-wrench"></span> </a>
                        </td>
                        <td>
                            <a href="{% url 'blog:article_delete' article.id article.slug %}"><span class="glyphicon glyphicon-trash"></span> </a>
                        </td>
                  {% endfor %}
                    </tr>


                </tbody>
                <tfoot>

                </tfoot>
            </table>
        {% else %}
            <p>没有文章</p>
        {% endif %}

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
        </div>
    <!-- /.col -->
      </div>
    <!-- /.row -->
    </section>

{% endblock %}

{% block script %}

<!-- DataTables -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'AdminLTE-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- page script -->
<script>
    $(function () {
        $('#blog').DataTable({
             "paging"      : true,       <!-- 允许分页 -->
             "lengthChange": true,       <!-- 允许改变每页显示的行数 -->
             "searching"   : true,       <!-- 允许内容搜索 -->
             "ordering"    : true,       <!-- 允许排序 -->
             "info"        : true,       <!-- 显示信息 -->
             "autoWidth"   : true,       <!-- 固定宽度 -->



             "pagingType"  : "full_numbers",  <!-- 显示尾页和首页 -->

              "language": {
                        //"info": "当前第_PAGE_页，共 _PAGES_页",
                        "sInfo": "当前显示第 _START_ 到第 _END_ 条，共 _TOTAL_ 条",
                        "sInfoFiltered": "(从_MAX_条筛选 )",
                        "sInfoEmpty": "共筛选到0条",
                        "sSearch": "搜索:",
                        "sLengthMenu": "每页显示 _MENU_ 条",
                        "sZeroRecords": "未筛选到相关内容",
                        "paginate": {
                            "sFirst": "首页",  //首页和尾页必须在pagingType设为full_numbers时才可以
                            "sLast": "尾页",
                            "sPrevious": "上一页",
                            "sNext": "下一页",
                            "first": "First page",
                            "last": "Last page",
                            "next": "Next page",
                            "previous": "Previous page"
                        }

              }
        });
        $('#evaluate').colResizable({
            liveDrag: true, //实现实时拖动，可看见拖动轨迹
            draggingClass: "dragging", //防止拖动出现虚标线
            resizeMode: 'flex',
        });
    });

</script>

{% endblock %}