blog/urls.py
# -*- coding: utf-8 -*-
"""
#Python 3.6
-------------------------------------------------
   Project Name:    securityproject
   File Name:       urls.py
   Description :
   Author :         flowerhost
   date:            2020/5/6          
-------------------------------------------------
   Change Activity:
                    2020/5/6:
-------------------------------------------------
"""
__author__ = 'flowerhost'

"""定义blog的URL模式"""

from django.urls import path, re_path

from . import views

# 在2.1版本中必须增加的一条代码
app_name = 'blog'

urlpatterns = [
    # 所有文章列表
    path('', views.ArticleListView.as_view(), name='article_list'),
    # 展示文章详情
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
    # 草稿箱
    path('draft/', views.ArticleDraftListView.as_view(), name='article_draft_list'),
    # 已发表文章列表（含编辑）
    path('published/', views.PublishedArticleListView.as_view(), name='published_article_list'),
    # 更新文章
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/update/$', views.ArticleUpdateView.as_view(),
            name='article_update'),
    # 创建文章
    re_path(r'^article/create/$', views.ArticleCreateView.as_view(), name='article_create'),
    # 发表文章
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/publish/$', views.article_publish, name='article_publish'),
    #  删除文章
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/delete$', views.ArticleDeleteView.as_view(),
            name='article_delete'),
    # 展示类别列表
    # re_path(r'^category/$',
    #         views.ArticleDraftListView.as_view(), name='category_list'),

    # 展示类别详情
    re_path(r'^category/(?P<slug>[-\w]+)/$',
            views.CategoryDetailView.as_view(), name='category_detail'),

]

securityproject/urls.py
from django.contrib import admin
from django.urls import include, path
# 2020-05-06 新增bolg app
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('index/', include('capital_management.urls', namespace='capital_management')),
    path('captcha', include('captcha.urls')),  # 登陆界面图形验证功能
    path('select2/', include('select2.urls')),  # 下拉菜单筛选功能
    path('blog/', include('blog.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""为应用程序users定义URLS模式"""

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # 登录界面
    path('', views.login, name='login'),
    path('register', views.register, name='register'),
    path('share/', views.share, name='share'),

]

users/models.py
from django.db import models

from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    org = models.CharField('Organization', max_length=128, blank=True)
    telephone = models.CharField('Telephone', max_length=50, blank=True)
    modify_date = models.DateTimeField('Last modified', auto_now=True)

    class Meta:
        verbose_name = 'User Profile'

    def __str__(self):
        return self.user

users/forms.py
from django import forms
from django.contrib.auth.models import User
from captcha.fields import CaptchaField
import re


def email_check(email):
    pattern = re.compile(r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
    return re.match(pattern, email)


class RegistrationForm(forms.Form):

    username = forms.CharField(label='用户名', max_length=50)
    email = forms.EmailField(label='电子邮箱')
    password1 = forms.CharField(label='密码', widget=forms.PasswordInput)
    password2 = forms.CharField(label='密码验证', widget=forms.PasswordInput)

    username.widget.attrs.update({'style': 'width:100%', 'placeholder': '用户名'})
    email.widget.attrs.update({'style': 'width:100%', 'placeholder': '电子邮箱'})
    password1.widget.attrs.update({'style': 'width:100%', 'placeholder': '密码'})
    password2.widget.attrs.update({'style': 'width:100%', 'placeholder': '密码验证'})

    # 使用 clean类来定义用户验证规则
    def clean_username(self):
        username = self.cleaned_data.get('username')

        if len(username) < 6:
            raise forms.ValidationError("你的用户名须超过6个字符！")
        elif len(username) > 50:
            raise forms.ValidationError("你的用户名太长啦！")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if len(filter_result) > 0:
                raise forms.ValidationError("你的用户名已存在！")

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email_check(email):
            filter_result = User.objects.filter(email__exact=email)
            if len(filter_result) > 0:
                raise forms.ValidationError("你的邮箱已存在！")
        else:
            raise forms.ValidationError("请输入有效邮箱地址！")

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if len(password1) < 6:
            raise forms.ValidationError("你的密码太短啦！")
        elif len(password1) > 20:
            raise forms.ValidationError("你的密码太长啦！")

        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("密码输入不一致！请再次输入！")

        return password2


class LoginForm(forms.Form):

    username = forms.CharField(label='用户名', max_length=50)
    password = forms.CharField(label='密码', widget=forms.PasswordInput)
    captcha = CaptchaField(label='验证码')

    username.widget.attrs.update({'style': 'width:100%', 'placeholder': '用户名'})
    password.widget.attrs.update({'style': 'width:100%', 'placeholder': '密码'})
    captcha.widget.attrs.update({'style': 'width:55%'})

    # 使用 clean类来定义用户验证规则
    def clean_username(self):
        username = self.cleaned_data.get('username')

        if email_check(username):
            filter_result = User.objects.filter(email__exact=username)
            if not filter_result:
                raise forms.ValidationError("邮箱地址不存在！")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if not filter_result:
                raise forms.ValidationError("用户名不存在！请注册！")

        return username

users/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User

from .forms import LoginForm, RegistrationForm


def login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                auth.login(request, user)
                return redirect('capital_management:dashboard')

            else:
                return render(request, 'users/login.html', {'login_form': login_form, 'message': '密码错误！请重新输入。'})

    else:
        login_form = LoginForm()

    return render(request, 'users/login.html', {'login_form': login_form})


def register(request):
    if request.method == 'POST':
        register_form = RegistrationForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            email = register_form.cleaned_data['email']
            password = register_form.cleaned_data['password2']

            User.objects.create_user(username=username, password=password, email=email)

            # user profile表的操作
            # user_profile = UserProfile(user=user)
            # user_profile.save()

            return render(request, 'users/share.html', {'register_form': register_form})
    else:
        register_form = RegistrationForm()

    return render(request, 'users/register.html', {'register_form': register_form})


def share(request):
    return render(request, 'users/share.html')

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>证券资产管理系统 | 登录</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
      <a href="http://www.flowerhost.com"><b>证券资产管理系统</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
      <p class="login-box-msg"><b>登录管理系统</b></p>

    <form action="{% url 'users:login' %}" method="post">
      {% if message %}
        <div class="alert alert-warning">{{ message }}</div>
      {% endif %}
      {% csrf_token %}
      <div class="form-group has-feedback">
          {{ login_form.username.label_tag }}
          {{ login_form.username }}
      </div>
      <div class="form-group has-feedback" >
          {{ login_form.password.label_tag }}
          {{ login_form.password }}
      </div>
      <div class="form-group has-feedback">
          {{ login_form.captcha.label_tag }}
          {{ login_form.captcha }}
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <a href="{% url 'users:register' %}" class="text-success"><ins>新用户注册</ins></a>
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">

          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'AdminLTE-2.4.10/plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>证券资产管理系统 | 注册</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="www.flowerhost.com"><b>证券资产管理系统</b></a>
  </div>

  <div class="register-box-body">
      <p class="login-box-msg"><b>注册新账号</b></p>

    <form action="{% url 'users:register' %}" method="post">
      {% csrf_token %}
      {{ form.errors }}
      <div class="form-group has-feedback">
          {{ register_form }}
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> 我同意 <a href="#">所有条款</a>
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">注册</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <a href="{% url 'users:login' %}" class="text-center">我已有一个账号</a>
  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->

<!-- jQuery 3 -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'AdminLTE-2.4.10/plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

templates/users/share.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>证券资产管理系统 | 注册</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.10/plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="www.flowerhost.com"><b>证券资产管理系统</b></a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">注册结果</p>

    <form action="{% url 'users:login' %}" >
      {% csrf_token %}
      {% if form.username %}
          <div class="alert alert-warning">注册失败！{{ form.username }}已存在</div>
          <a href="{% url 'users:register' %}">注册</a>
      {% else %}
          <div class="alert alert-warning">注册成功!</div>
      {% endif %}
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> 记住我
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>

    </form>
  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->

<!-- jQuery 3 -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'AdminLTE-2.4.10/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'AdminLTE-2.4.10/plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>